POST /api/2.5/lots/d66e3d4476144d8bbdd201b4a80f480b/related_processes HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 83
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
X-Access-Token: 295fc83d59cc4905968796f48dbbcbfb
DATA:
{
  "data": {
    "type": "asset", 
    "relatedProcessID": "ad0a74947d804f809597c5d42a92a31f"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.5/lots/d66e3d4476144d8bbdd201b4a80f480b/related_processes/8352df3d3c0e490ebe1773cfdceeefa9
X-Content-Type-Options: nosniff
{
  "data": {
    "type": "asset", 
    "id": "8352df3d3c0e490ebe1773cfdceeefa9", 
    "relatedProcessID": "ad0a74947d804f809597c5d42a92a31f"
  }
}

