PATCH /api/2.5/lots/9c54261550f74c99b25b7a8ab16aa97a/auctions/cb14fea47f324446b083099e026b1de4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 449
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
X-Access-Token: 53ce42a01cb745819303b64031afbb2b
DATA:
{
  "data": {
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 300.87, 
      "valueAddedTaxIncluded": true
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 3000.87, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "startDate": "2019-03-25T15:28:05.257425+02:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "scheduled", 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 300.87, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "startDate": "2019-03-25T15:28:05.257425+02:00"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "sellout.english", 
    "value": {
      "currency": "UAH", 
      "amount": 3000.87, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionParameters": {
      "type": "english"
    }, 
    "id": "cb14fea47f324446b083099e026b1de4", 
    "guarantee": {
      "currency": "UAH", 
      "amount": 700.87
    }
  }
}

