PATCH /api/2.5/lots/ce437a4384f44fcdb5b75f9675ca0a82/auctions/7fc01ac1e0444a5e844ca954c2e5e418 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
X-Access-Token: 43027267d2f645f9b1e36244f6d8a207
DATA:
{
  "data": {
    "tenderingDuration": "P25DT12H"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "scheduled", 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 150.44, 
      "valueAddedTaxIncluded": true
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "procurementMethodType": "sellout.english", 
    "value": {
      "currency": "UAH", 
      "amount": 1500.43, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderingDuration": "P25DT12H", 
    "id": "7fc01ac1e0444a5e844ca954c2e5e418", 
    "auctionParameters": {
      "type": "english"
    }, 
    "tenderAttempts": 2, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 350.44
    }
  }
}

