PATCH /api/2.5/lots/9c54261550f74c99b25b7a8ab16aa97a/auctions/5bbdebcd2d9748aa89220f01f17a18f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
X-Access-Token: 53ce42a01cb745819303b64031afbb2b
DATA:
{
  "data": {
    "tenderingDuration": "P25DT12H"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "scheduled", 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 150.44, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderAttempts": 2, 
    "procurementMethodType": "sellout.english", 
    "value": {
      "currency": "UAH", 
      "amount": 1500.44, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderingDuration": "P25DT12H", 
    "auctionParameters": {
      "type": "english"
    }, 
    "id": "5bbdebcd2d9748aa89220f01f17a18f3", 
    "guarantee": {
      "currency": "UAH", 
      "amount": 350.44
    }
  }
}

