GET /api/0.1/lots/ac8842f3a2154890a356ca6513d122c0 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "active.salable", 
    "lotIdentifier": "Q81318b19827", 
    "lotID": "UA-LR-DGF-2018-01-09-000003", 
    "description": "Щось там тестове", 
    "title": "Тестовий лот", 
    "lotType": "basic", 
    "dateModified": "2018-01-09T17:32:39.840258+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "date": "2018-01-09T17:32:39.840085+02:00", 
    "id": "ac8842f3a2154890a356ca6513d122c0", 
    "assets": [
      "6484266ec5e04fc6842b4f69151101c0"
    ]
  }
}

