GET /api/0.1/lots/2a7be98ad5ef415f8d0bc3e7097455b7 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "sold", 
    "lotIdentifier": "Q81318b19827", 
    "lotID": "UA-LR-DGF-2018-01-15-000004", 
    "description": "Щось там тестове", 
    "title": "Тестовий лот", 
    "lotType": "basic", 
    "dateModified": "2018-01-15T15:30:23.436290+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "date": "2018-01-15T15:30:23.436074+02:00", 
    "id": "2a7be98ad5ef415f8d0bc3e7097455b7", 
    "assets": [
      "ebfcf7438665460dad30ff5e6a8a3127"
    ]
  }
}

