POST /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 318
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "lotType": "loki", 
    "decisions": [
      {
        "decisionDate": "2019-03-19T15:23:06.251270+02:00", 
        "decisionID": "initialDecisionID"
      }
    ], 
    "description": "Щось там тестове", 
    "title": "Тестовий лот"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/lots/2f6e750402f841beb513d413240b60a0
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "c78f6adea1ec45e6951ac1e2891b11fb", 
    "token": "be16a40e2003457aaac2d58b80cbc527"
  }, 
  "data": {
    "status": "draft", 
    "lotID": "UA-LR-DGF-2019-03-19-000003", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "ebe5f45c1bcd40179b96db1f03754c29"
      }
    ], 
    "lotType": "loki", 
    "dateModified": "2019-03-19T15:23:06.649265+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-19T15:23:06.639379+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-19T15:23:06.639405+02:00", 
        "id": "b6e7ae98101d4a50a6f32ced0c1cf4df"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "50b55e1ba3c34779b26a22527292eb52"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "1f49c1f5f38848cb807c52e191c0cde4"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "id": "c95266b3c5e64a8fa40049302b5bd499"
      }
    ], 
    "date": "2019-03-19T15:23:06.647458+02:00", 
    "decisions": [
      {
        "decisionDate": "2019-03-19T15:23:06.251270+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "ec2d6fb65a9241baab975993c550f7dd", 
        "decisionOf": "lot"
      }
    ], 
    "id": "2f6e750402f841beb513d413240b60a0"
  }
}

