GET /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "next_page": {
    "path": "/api/2.5/lots?offset=2019-03-19T15%3A23%3A06.588340%2B02%3A00", 
    "uri": "http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/lots?offset=2019-03-19T15%3A23%3A06.588340%2B02%3A00", 
    "offset": "2019-03-19T15:23:06.588340+02:00"
  }, 
  "data": [
    {
      "id": "9c54261550f74c99b25b7a8ab16aa97a", 
      "dateModified": "2019-03-19T15:23:06.588340+02:00"
    }
  ]
}

