GET /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "next_page": {
    "path": "/api/2.5/lots?offset=2018-08-21T17%3A17%3A27.823632%2B03%3A00", 
    "uri": "http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.5/lots?offset=2018-08-21T17%3A17%3A27.823632%2B03%3A00", 
    "offset": "2018-08-21T17:17:27.823632+03:00"
  }, 
  "data": [
    {
      "id": "ea37278d119147d3bad3442da5f4c342", 
      "dateModified": "2018-08-21T17:17:27.823632+03:00"
    }
  ]
}

