PATCH /api/0.1/lots/def2b43f991d47319cbf18b2631df5a1?acc_token=b6bac0414e514d3ab9dd3ab1b772a90d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending", 
    "lotID": "UA-LR-DGF-2017-09-27-000001", 
    "description": "Щось там тестове", 
    "title": "Тестовий лот", 
    "lotType": "basic", 
    "dateModified": "2017-09-27T16:00:29.181044+03:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "date": "2017-09-27T16:00:29.180875+03:00", 
    "id": "def2b43f991d47319cbf18b2631df5a1", 
    "assets": [
      "d336c262c697423eb947c8628900f056"
    ]
  }
}

