GET /api/2.5/lots/cee33af034594b0cab94046740c95c6b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "deleted", 
    "rectificationPeriod": {
      "startDate": "2019-02-04T16:38:19.591458+02:00", 
      "endDate": "2019-02-06T16:38:19.591458+02:00"
    }, 
    "lotID": "UA-LR-DGF-2019-02-04-000002", 
    "description": "Нежитлове приміщення для збереження насіння", 
    "title": "Нежитлове приміщення", 
    "contracts": [
      {
        "status": "cancelled", 
        "type": "yoke", 
        "id": "7840d66d09db455aadbcfe961ffa22a4"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "loki", 
    "lotHolder": {
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Власник лоту"
    }, 
    "decisions": [
      {
        "decisionDate": "2019-02-04T16:38:19.078303+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "97fb062d1fc04f6dae473a42caf7880b", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "35e8b82cc8dd4f5aa8d3036333587f6e", 
        "decisionDate": "2019-02-04T16:38:19.381718+02:00", 
        "decisionID": "11111-4-5", 
        "id": "01218fffebf7420297e6eea9a784799e", 
        "decisionOf": "asset"
      }
    ], 
    "dateModified": "2019-02-04T16:38:19.937920+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Сергій", 
        "email": "segiy@mail.com"
      }, 
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Зберігач лоту", 
      "address": {
        "countryName": "Україна"
      }
    }, 
    "auctions": [
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2019-02-08T16:43:16.610865+02:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "f75a4ee302e248ce8011d5eb89cab577", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }, 
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.44, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "89fe0464391a4b7191ac69cfd57ec7b7", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }, 
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "f8ea1544ac9440c99728cea6f6470e85", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }
    ], 
    "date": "2019-02-04T16:38:19.937742+02:00", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-04T16:38:19.083999+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-04T16:38:19.084020+02:00", 
        "id": "5740aeb9d2634f1baea9348de36a587a"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "lot_owner", 
        "title": "укр.doc", 
        "url": "http://localhost/get/d1b60a17aa6947f7af224e9e167f67c7?KeyID=172d32c8&Signature=cdekvRRIIgbd%252Bi8YBsiox4L1Wxx0N1ivhcnmJq7rpXJzYeeSXw9uL8yJ07nDblHrqNWbmFXIEE2oa%252BFJFvvBDw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "lot", 
        "datePublished": "2019-02-04T16:38:19.684473+02:00", 
        "documentType": "cancellationDetails", 
        "dateModified": "2019-02-04T16:38:19.684492+02:00", 
        "id": "0e09490b8c5b4fb4a92cb8fee71bbf10"
      }
    ], 
    "relatedProcesses": [
      {
        "identifier": "UA-AR-P-2018-08-17-000002-1", 
        "type": "asset", 
        "id": "0757f335629d494a88469b86de4946f7", 
        "relatedProcessID": "f6b145270b8a4400bc89985051848187"
      }
    ], 
    "id": "cee33af034594b0cab94046740c95c6b"
  }
}

