POST /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 415
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "decisions": [
      {
        "decisionDate": "2018-08-21T17:17:27.417194+03:00", 
        "decisionID": "initialDecisionID"
      }
    ], 
    "lotType": "loki", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "relatedProcessID": "78456d2cb60842c392a65c1272e52077"
      }
    ], 
    "description": "Щось там тестове", 
    "title": "Тестовий лот"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.5/lots/20d058d811884303a8452d7bd4dd49e2
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "de421240bb3c464aad2f6b14751ad149", 
    "token": "21b27f90714249f4a6004788b3176d8f"
  }, 
  "data": {
    "status": "draft", 
    "lotID": "UA-LR-DGF-2018-08-21-000001", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "759727d026d04cf7b16fcd10abc612ff"
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2018-08-21T17:17:27.417194+03:00", 
        "decisionID": "initialDecisionID", 
        "id": "ac96914428c0448992903475b9e46960", 
        "decisionOf": "lot"
      }
    ], 
    "lotType": "loki", 
    "dateModified": "2018-08-21T17:17:27.458188+03:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2018-08-21T17:17:27.444096+03:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2018-08-21T17:17:27.444125+03:00", 
        "id": "591909ec57634a10b24f2ccd2eb16d27"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "id": "2f50a59c920a46f687d92560baa89465", 
        "auctionParameters": {
          "type": "english"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 744.6
        }
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "id": "66f9e1de308b44ceb7adad40f2f83d65", 
        "auctionParameters": {
          "type": "english"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 744.6
        }
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "id": "f70611babbb142118f5e53d3c49bf6ed", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 744.6
        }
      }
    ], 
    "date": "2018-08-21T17:17:27.456370+03:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "ceb86d4997ba43858e92ff7a4256078c", 
        "relatedProcessID": "78456d2cb60842c392a65c1272e52077"
      }
    ], 
    "id": "20d058d811884303a8452d7bd4dd49e2"
  }
}

