PATCH /api/2.4/lots/1947689f874148418bdd871ed5efe21f?acc_token=7911aa2b190c4039bc8d6c030cdbd101 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "composing"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "composing", 
    "lotID": "UA-LR-DGF-2018-05-25-000001", 
    "assets": [
      "964e194e98b14d1da03fc48be7865221"
    ], 
    "lotType": "loki", 
    "dateModified": "2018-05-25T17:28:38.446493+03:00", 
    "owner": "broker", 
    "auctions": [
      {
        "status": "scheduled", 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "27a5b1b2ac30456b86e25e7c152b55c6"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "5f0dcb4cb3c6436c85af7ce3ee949d44"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "id": "0a87e459dd3b438a92d35d7de855b948"
      }
    ], 
    "date": "2018-05-25T17:28:38.446249+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-05-25T17:28:37.300221+03:00", 
        "decisionID": "decisionLotID"
      }
    ], 
    "id": "1947689f874148418bdd871ed5efe21f"
  }
}

