PATCH /api/2.5/lots/962fa6efd16d4d55acd4b1f88bb7cec9?acc_token=f3e126c1e7734b1b8887cfbf17478baa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 39
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "status": "pending.deleted"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending.deleted", 
    "rectificationPeriod": {
      "startDate": "2019-02-04T16:38:18.269804+02:00", 
      "endDate": "2019-02-06T16:38:18.269804+02:00"
    }, 
    "lotID": "UA-LR-DGF-2019-02-04-000002", 
    "description": "Нежитлове приміщення для збереження насіння", 
    "title": "Нежитлове приміщення", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "1f33640dca2f43b48787d5bceacb577a"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "loki", 
    "lotHolder": {
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Власник лоту"
    }, 
    "decisions": [
      {
        "decisionDate": "2019-02-04T16:38:17.514327+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "5d1a237b9525459d9262153c5ae5cb5f", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "2a30936173c74e0495d058a5c31044c7", 
        "decisionDate": "2019-02-04T16:38:18.066068+02:00", 
        "decisionID": "11111-4-5", 
        "id": "9d55bffaeced49a9bdb6b53315fa050a", 
        "decisionOf": "asset"
      }
    ], 
    "dateModified": "2019-02-04T16:38:18.487081+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Сергій", 
        "email": "segiy@mail.com"
      }, 
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Зберігач лоту", 
      "address": {
        "countryName": "Україна"
      }
    }, 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2019-02-08T16:43:16.610865+02:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "11f0bee4cf814e36b91ede32155fce67", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }, 
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.44, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "ec32cd417be24997af164a661733756d", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }, 
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "fe87453d392845819b75c11d66cc414d", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }
    ], 
    "date": "2019-02-04T16:38:18.486885+02:00", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-04T16:38:17.586506+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-04T16:38:17.586543+02:00", 
        "id": "fa6b62b6f5e2400d963dd502d2d83623"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "lot_owner", 
        "title": "укр.doc", 
        "url": "http://localhost/get/48050771eb984a409570e74376eb5b2b?KeyID=172d32c8&Signature=ej%2F8G%252B24t1Fu1zN2kxRy%2F2nR1569zAny9URT43NxthpXxlvtHba1g9HgTyZanWuwDjF60X8ZIIveYTZw5ZisBw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "lot", 
        "datePublished": "2019-02-04T16:38:18.363290+02:00", 
        "documentType": "cancellationDetails", 
        "dateModified": "2019-02-04T16:38:18.363310+02:00", 
        "id": "ba0b14ec636c4082b4a85630d44169cd"
      }
    ], 
    "relatedProcesses": [
      {
        "identifier": "UA-AR-P-2018-08-17-000002-1", 
        "type": "asset", 
        "id": "c9dd31ba70cf485fa30231f3a19a81dc", 
        "relatedProcessID": "a9cbac9550db413284dcfbbf9f9cd028"
      }
    ], 
    "id": "962fa6efd16d4d55acd4b1f88bb7cec9"
  }
}

