PATCH /api/2.4/lots/1947689f874148418bdd871ed5efe21f?acc_token=7911aa2b190c4039bc8d6c030cdbd101 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 39
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "pending.deleted"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending.deleted", 
    "rectificationPeriod": {
      "startDate": "2018-05-25T17:29:18.999808+03:00", 
      "endDate": "2018-05-27T17:29:18.999808+03:00"
    }, 
    "lotID": "UA-LR-DGF-2018-05-25-000001", 
    "assets": [
      "964e194e98b14d1da03fc48be7865221"
    ], 
    "lotType": "loki", 
    "dateModified": "2018-05-25T17:29:19.209959+03:00", 
    "owner": "broker", 
    "documents": [
      {
        "dateModified": "2018-05-25T17:29:19.081412+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://localhost/get/684665392c3c4e2baad7eb3ec5b8e05e?KeyID=172d32c8&Signature=%252BnGVFJ6S39dOayEwTfaQx81FpXtMGFFzy0fsW7gtUWuoRbJ%252Blxy19EYr01%2FC%252B3G8xrfAPDQqgcC8PqvF4754Aw%253D%253D", 
        "author": "lot_owner", 
        "documentOf": "lot", 
        "datePublished": "2018-05-25T17:29:19.081378+03:00", 
        "documentType": "cancellationDetails", 
        "title": "укр.doc", 
        "id": "76526af5ecff419d9c9c3e28693d7e2f"
      }
    ], 
    "next_check": "2018-05-27T17:29:18.999808+03:00", 
    "auctions": [
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2018-05-30T17:28:37.300003+03:00", 
          "endDate": "2018-06-04T17:28:37.300003+03:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.0
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "27a5b1b2ac30456b86e25e7c152b55c6", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.0
        }
      }, 
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 350.0
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "5f0dcb4cb3c6436c85af7ce3ee949d44", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.0
        }
      }, 
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 350.0
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "0a87e459dd3b438a92d35d7de855b948", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.0
        }
      }
    ], 
    "date": "2018-05-25T17:29:19.209691+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-05-25T17:28:37.300221+03:00", 
        "decisionID": "decisionLotID"
      }, 
      {
        "decisionDate": "2018-05-25T17:29:18.820239+03:00", 
        "decisionID": "decisionAssetID"
      }
    ], 
    "id": "1947689f874148418bdd871ed5efe21f"
  }
}

