GET /api/2.5/lots/04ecebe1469a426aa854c2feab78b151 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "sold", 
    "rectificationPeriod": {
      "startDate": "2018-08-14T19:15:25.748036+03:00", 
      "endDate": "2018-08-15T19:15:25.748036+03:00"
    }, 
    "lotID": "UA-LR-DGF-2018-08-17-000004", 
    "title": "title", 
    "contracts": [
      {
        "status": "complete", 
        "type": "yoke", 
        "id": "6e6968f86b5043429595b4d6a7284351"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "loki", 
    "decisions": [
      {
        "decisionDate": "2018-08-17T19:15:25.772636+03:00", 
        "decisionID": "decisionAssetID", 
        "id": "c18b98a2f1944e3dba7c9eb4aa799ff5", 
        "decisionOf": "lot"
      }, 
      {
        "decisionDate": "2018-08-17T19:15:25.772665+03:00", 
        "decisionID": "decisionAssetID", 
        "id": "902889483a2e442ea5a1e449a810bea9", 
        "decisionOf": "lot"
      }
    ], 
    "dateModified": "2018-08-17T19:15:26.304944+03:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2018-08-17T19:15:25.183049+03:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2018-08-17T19:15:25.183078+03:00", 
        "id": "d882a6085cf54aeaa1f777e62b76b637"
      }
    ], 
    "auctions": [
      {
        "status": "complete", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2018-08-23T19:20:19.767990+03:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "1b28f9152dbd41bfac2ae96281a45d38", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }, 
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.44, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.43, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "7a963db62e3e4407a1ccce90d5a5c5f3", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }, 
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0.0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.43, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "a5eaf79f5600439290585f6b6ddfd91a", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }
    ], 
    "date": "2018-08-17T19:15:26.304750+03:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "c21eeffaf1ac459d8f226077f7171c95", 
        "relatedProcessID": "e7844d63d12f465194c084bea990f4b9"
      }
    ], 
    "id": "04ecebe1469a426aa854c2feab78b151"
  }
}

