GET /api/2.4/lots HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "next_page": {
    "path": "/api/2.4/lots?offset=2018-05-25T17%3A28%3A38.807676%2B03%3A00", 
    "uri": "http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.4/lots?offset=2018-05-25T17%3A28%3A38.807676%2B03%3A00", 
    "offset": "2018-05-25T17:28:38.807676+03:00"
  }, 
  "data": [
    {
      "id": "1947689f874148418bdd871ed5efe21f", 
      "dateModified": "2018-05-25T17:28:38.651411+03:00"
    }, 
    {
      "id": "d643a4ad34414779a15fc9c00c229efa", 
      "dateModified": "2018-05-25T17:28:38.807676+03:00"
    }
  ]
}

