GET /api/2.5/lots/c388bd047cb84a448395630ee4474b7a HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "invalid", 
    "lotID": "UA-LR-DGF-2019-03-19-000001", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "a9a7c8ecd9d2419db7018de9c4acb6be"
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-03-19T15:23:07.304009+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "eb840f04e0f949548bd88357c68547bf", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "11111111111111111111111111111111", 
        "decisionDate": "2019-03-19T15:23:07.596709+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "267cc390b8ef45378f2c38f09569296c", 
        "decisionOf": "asset"
      }
    ], 
    "lotType": "loki", 
    "dateModified": "2019-03-19T15:23:07.742936+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-19T15:23:07.313166+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-19T15:23:07.313199+02:00", 
        "id": "b75c4c3306b94f6b9e9277612e2a3224"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2019-03-25T15:28:05.257425+02:00"
        }, 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "a3568f1cef0b463685caa76a28da0ad9", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }, 
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "a44d3c074c144772b6750d9e930569f0", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }, 
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "id": "8947ade7f6144d4bb0eabeaf5a742885", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }
    ], 
    "date": "2019-03-19T15:23:07.742763+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "f8e798b3883f43fd803a555f3e677e50", 
        "relatedProcessID": "548ddf2bfca74136ba83cb6339ad3ca8"
      }
    ], 
    "id": "c388bd047cb84a448395630ee4474b7a"
  }
}

