GET /api/2.5/lots/7a664c41089f40e3836284db2f4ac963 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "sold", 
    "rectificationPeriod": {
      "startDate": "2019-02-01T16:38:21.833935+02:00", 
      "endDate": "2019-02-02T16:38:21.833935+02:00"
    }, 
    "lotID": "UA-LR-DGF-2019-02-04-000004", 
    "title": "title", 
    "contracts": [
      {
        "status": "complete", 
        "type": "yoke", 
        "id": "d8bd7e5bc39c4653a37d762ccfd0d963"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "loki", 
    "decisions": [
      {
        "decisionDate": "2019-02-04T16:38:21.849671+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "14a8295ad72747a1b4d8b1ca2de90d7b", 
        "decisionOf": "lot"
      }, 
      {
        "decisionDate": "2019-02-04T16:38:21.849690+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "843f1c97f5964f51bb481192f206e163", 
        "decisionOf": "lot"
      }
    ], 
    "dateModified": "2019-02-04T16:38:22.331036+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-04T16:38:21.324619+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-04T16:38:21.324638+02:00", 
        "id": "64d66805b9ee487f909e389871b0c08a"
      }
    ], 
    "auctions": [
      {
        "status": "complete", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2019-02-08T16:43:16.610865+02:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "efda1f6b06fd4d36a19b4ae5522bda40", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }, 
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.44, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "8086d12b6e3f4fbbaa49265006d77aac", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }, 
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "ed5031bd4abc4e2ab989d6fe2fe2b13a", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }
    ], 
    "date": "2019-02-04T16:38:22.330860+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "94d56e09a8e847f4bbedbea1c6c0b159", 
        "relatedProcessID": "e6dffe2398e64b54ae6fa6b1a581dfaa"
      }
    ], 
    "id": "7a664c41089f40e3836284db2f4ac963"
  }
}

