POST /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 318
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "lotType": "loki", 
    "decisions": [
      {
        "decisionDate": "2019-03-19T15:23:06.251270+02:00", 
        "decisionID": "initialDecisionID"
      }
    ], 
    "description": "Щось там тестове", 
    "title": "Тестовий лот"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/lots/9c54261550f74c99b25b7a8ab16aa97a
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "3ee8b7f4bb8647c684cf8a318332650c", 
    "token": "53ce42a01cb745819303b64031afbb2b"
  }, 
  "data": {
    "status": "draft", 
    "lotID": "UA-LR-DGF-2019-03-19-000002", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "eb92ac079d3945c9ae2d6a8c31877c3f"
      }
    ], 
    "lotType": "loki", 
    "dateModified": "2019-03-19T15:23:06.324966+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-19T15:23:06.314674+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-19T15:23:06.314696+02:00", 
        "id": "b5506c8a9353481f8e6fcc964242ea79"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "cb14fea47f324446b083099e026b1de4"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "5bbdebcd2d9748aa89220f01f17a18f3"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "id": "b2998f0368c340609fa56fa0a12fdcfa"
      }
    ], 
    "date": "2019-03-19T15:23:06.323072+02:00", 
    "decisions": [
      {
        "decisionDate": "2019-03-19T15:23:06.251270+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "88efebe2abf542319f0a79b3645f5d9e", 
        "decisionOf": "lot"
      }
    ], 
    "id": "9c54261550f74c99b25b7a8ab16aa97a"
  }
}

