GET /api/0.1/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "next_page": {
    "path": "/api/0.1/lots?offset=2017-09-27T16%3A00%3A29.219961%2B03%3A00", 
    "uri": "http://lb.api-sandbox.registry.ea.openprocurement.net/api/0.1/lots?offset=2017-09-27T16%3A00%3A29.219961%2B03%3A00", 
    "offset": "2017-09-27T16:00:29.219961+03:00"
  }, 
  "data": [
    {
      "id": "def2b43f991d47319cbf18b2631df5a1", 
      "dateModified": "2017-09-27T16:00:29.219961+03:00"
    }
  ]
}

