GET /api/2.5/lots/78847efb7a4544b288a101c50282b32f HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "sold", 
    "rectificationPeriod": {
      "startDate": "2019-03-16T15:23:10.808388+02:00", 
      "endDate": "2019-03-17T15:23:10.808388+02:00"
    }, 
    "lotID": "UA-LR-DGF-2019-03-19-000004", 
    "title": "title", 
    "contracts": [
      {
        "status": "complete", 
        "type": "yoke", 
        "id": "eb7f4846ce0649eb80f7ddc9b409c159"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "loki", 
    "decisions": [
      {
        "decisionDate": "2019-03-19T15:23:10.834866+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "cc73e0efa39e442194fe22b933aa49ff", 
        "decisionOf": "lot"
      }, 
      {
        "decisionDate": "2019-03-19T15:23:10.834916+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "ae5f51ffd3524b5783acaa8825d91977", 
        "decisionOf": "lot"
      }
    ], 
    "dateModified": "2019-03-19T15:23:11.384119+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-19T15:23:10.301240+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-19T15:23:10.301269+02:00", 
        "id": "919434ff06d240f5b93621bb95943198"
      }
    ], 
    "auctions": [
      {
        "status": "complete", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2019-03-25T15:28:05.257425+02:00"
        }, 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "a301bd1cc7f44a8db01d91b52d718e1d", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }, 
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "8bb8705d77544107be729fc9fceb69b8", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }, 
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "id": "edf5fa678a554a6093474574bedec1e0", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }
    ], 
    "date": "2019-03-19T15:23:11.383758+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "581fa2649b454b40b9f81c9bb39cb7d7", 
        "relatedProcessID": "93cc092b92fb4f30898ffe69ca617e17"
      }
    ], 
    "id": "78847efb7a4544b288a101c50282b32f"
  }
}

