POST /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 415
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "decisions": [
      {
        "decisionDate": "2019-03-19T15:23:06.251270+02:00", 
        "decisionID": "initialDecisionID"
      }
    ], 
    "lotType": "loki", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "relatedProcessID": "72540e20491643c2a51141f419324344"
      }
    ], 
    "description": "Щось там тестове", 
    "title": "Тестовий лот"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/lots/75d059c9f53e4454b9b4f592b30ff566
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "003c8dea9ada4b869786f7bd09d81387", 
    "token": "95d8faca662844a48591e490390ef831"
  }, 
  "data": {
    "status": "draft", 
    "lotID": "UA-LR-DGF-2019-03-19-000001", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "f09354784c6848aaaffbd6ff38c87ef8"
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-03-19T15:23:06.251270+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "8a3dde028de144789c7f928df0cc32d2", 
        "decisionOf": "lot"
      }
    ], 
    "lotType": "loki", 
    "dateModified": "2019-03-19T15:23:06.291288+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-19T15:23:06.281066+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-19T15:23:06.281086+02:00", 
        "id": "f71092daf0f841d0a683a123e2456e21"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "a3aabb7301d64fef85a118762a7e7a26"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "ebd89717fe8c4856b2d4f322326b53af"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "id": "ed2964cad53246e6a5ffeb3609015607"
      }
    ], 
    "date": "2019-03-19T15:23:06.289301+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "2a94e1ee21fd45ef9188529643c9ca23", 
        "relatedProcessID": "72540e20491643c2a51141f419324344"
      }
    ], 
    "id": "75d059c9f53e4454b9b4f592b30ff566"
  }
}

