PATCH /api/2.5/lots/ea37278d119147d3bad3442da5f4c342?acc_token=2743b3ba5c844b4498ccb51233fc714b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "composing"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "composing", 
    "lotID": "UA-LR-DGF-2018-08-21-000002", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "8ea3d00b129c48e792e2c7c2339a4870"
      }
    ], 
    "lotType": "loki", 
    "dateModified": "2018-08-21T17:17:27.588390+03:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2018-08-21T17:17:27.485162+03:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2018-08-21T17:17:27.485189+03:00", 
        "id": "abc3a975dcf844deb027d02785a1aff5"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "id": "d61da6b1dcd64c4d83ebdc841190ece3", 
        "auctionParameters": {
          "type": "english"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 744.6
        }
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "id": "f2da3d4a5020423997f4ea91adf0c74a", 
        "auctionParameters": {
          "type": "english"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 744.6
        }
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "id": "80e86d8af7754472b017a05619822cc4", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 744.6
        }
      }
    ], 
    "date": "2018-08-21T17:17:27.588221+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-08-21T17:17:27.417194+03:00", 
        "decisionID": "initialDecisionID", 
        "id": "02658077e8564589a6ee9ad258c7801d", 
        "decisionOf": "lot"
      }
    ], 
    "id": "ea37278d119147d3bad3442da5f4c342"
  }
}

