POST /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 415
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "decisions": [
      {
        "decisionDate": "2019-02-04T16:38:17.514327+02:00", 
        "decisionID": "initialDecisionID"
      }
    ], 
    "lotType": "loki", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "relatedProcessID": "ea369adce3f04fa8acc8fcd1afa953c4"
      }
    ], 
    "description": "Щось там тестове", 
    "title": "Тестовий лот"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/lots/082937c0a9a943e6a66002f38d8ab164
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "91e654db1f7d494c85e264a5f30d94b9", 
    "token": "c4cfb45bcafc4e79a3b534602a96e697"
  }, 
  "data": {
    "status": "draft", 
    "lotID": "UA-LR-DGF-2019-02-04-000001", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "35ae4e36b10147e6a6ca4b0e314f654b"
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-02-04T16:38:17.514327+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "bfeb1c6300c842798e53866e615d3f06", 
        "decisionOf": "lot"
      }
    ], 
    "lotType": "loki", 
    "dateModified": "2019-02-04T16:38:17.554481+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-04T16:38:17.542498+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-04T16:38:17.542517+02:00", 
        "id": "6e14c66ae6774154a65580093cad49be"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "id": "8912e301d220436297bfee78d1c98f50", 
        "auctionParameters": {
          "type": "english"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 834.6
        }
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "id": "599d9e97d8e64c60aa8412e59815bda0", 
        "auctionParameters": {
          "type": "english"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 834.6
        }
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "id": "71ccc567557a4837a1a43565db8653d9", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 834.6
        }
      }
    ], 
    "date": "2019-02-04T16:38:17.552130+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "be09ce96c69a45a9bc419b0ba180392b", 
        "relatedProcessID": "ea369adce3f04fa8acc8fcd1afa953c4"
      }
    ], 
    "id": "082937c0a9a943e6a66002f38d8ab164"
  }
}

