PATCH /api/2.5/lots/7004db3cde7b4df3bc0c8166ec55c09b/auctions/ccd4bf0c1a4e4521ab27f447a7168999 HTTP/1.0
Authorization: Basic Y29udm95Og==
Content-Length: 33
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "cancelled", 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 300.87, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "startDate": "2018-08-23T14:56:45.642186+03:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "procurementMethodType": "sellout.english", 
    "value": {
      "currency": "UAH", 
      "amount": 3000.87, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "ccd4bf0c1a4e4521ab27f447a7168999", 
    "auctionParameters": {
      "type": "english"
    }, 
    "tenderAttempts": 1, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 700.87
    }
  }
}

GET /api/2.5/lots/7004db3cde7b4df3bc0c8166ec55c09b HTTP/1.0
Authorization: Basic Y29udm95Og==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending.dissolution", 
    "rectificationPeriod": {
      "startDate": "2018-08-14T14:51:49.356938+03:00", 
      "endDate": "2018-08-15T14:51:49.356938+03:00"
    }, 
    "lotID": "UA-LR-DGF-2018-08-17-000003", 
    "title": "title", 
    "contracts": [
      {
        "status": "cancelled", 
        "type": "yoke", 
        "id": "3160618903564fda81d4474ef56f6240"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "loki", 
    "decisions": [
      {
        "decisionDate": "2018-08-17T14:51:49.371861+03:00", 
        "decisionID": "decisionAssetID", 
        "id": "a439d33e7d984b7693b63c0d0c43bc76", 
        "decisionOf": "lot"
      }, 
      {
        "decisionDate": "2018-08-17T14:51:49.371888+03:00", 
        "decisionID": "decisionAssetID", 
        "id": "bf2ae36738f44810b250b54aac41a594", 
        "decisionOf": "lot"
      }
    ], 
    "dateModified": "2018-08-17T14:51:49.809986+03:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2018-08-17T14:51:48.783245+03:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2018-08-17T14:51:48.783272+03:00", 
        "id": "9c0d6e47321940fb91a26745b346781f"
      }
    ], 
    "auctions": [
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2018-08-23T14:56:45.642186+03:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "ccd4bf0c1a4e4521ab27f447a7168999", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }, 
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.44, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.43, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "a04252d598224e8585932814b354ab47", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }, 
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0.0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.43, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "0a83c17567bc465fa3c18739956fc1e0", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }
    ], 
    "date": "2018-08-17T14:51:49.809466+03:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "b2cc552603b6468abee95f3363162146", 
        "relatedProcessID": "2d4288ba924e404a8941c61603d31e32"
      }
    ], 
    "id": "7004db3cde7b4df3bc0c8166ec55c09b"
  }
}

