PATCH /api/2.4/lots/113a3b9fc6304fd9a3361b497a155042 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Content-Length: 33
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "dissolved"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "dissolved", 
    "rectificationPeriod": {
      "startDate": "2018-05-22T17:29:21.000575+03:00", 
      "endDate": "2018-05-23T17:29:21.000575+03:00"
    }, 
    "lotID": "UA-LR-DGF-2018-05-25-000005", 
    "assets": [
      "4ea8891f91674800aae50fbd13f49bce"
    ], 
    "title": "title", 
    "lotType": "loki", 
    "dateModified": "2018-05-25T17:29:21.508538+03:00", 
    "owner": "broker", 
    "next_check": "2018-05-23T17:29:21.000575+03:00", 
    "auctions": [
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2018-05-30T17:28:37.300003+03:00", 
          "endDate": "2018-06-04T17:28:37.300003+03:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.0
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "7a0e907be6ac43b184181017ea93f21d", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.0
        }
      }, 
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 350.0
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "9da3a4a5d582496b843578e3ae1186e2", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.0
        }
      }, 
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 350.0
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "02f235e16512412b9751d22946250a38", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.0
        }
      }
    ], 
    "date": "2018-05-25T17:29:21.508341+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-05-25T17:29:21.015938+03:00", 
        "decisionID": "decisionAssetID"
      }, 
      {
        "decisionDate": "2018-05-25T17:29:21.015969+03:00", 
        "decisionID": "decisionAssetID"
      }
    ], 
    "id": "113a3b9fc6304fd9a3361b497a155042"
  }
}

