PATCH /api/0.1/lots/34b371dc3b8f47a0869a8cac45be1181?acc_token=9791acb0d26647c48dd0a2570b7b53e3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 34
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "status": "recomposed"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "recomposed", 
    "lotIdentifier": "Q81318b19827", 
    "lotID": "UA-LR-DGF-2018-01-15-000005", 
    "description": "Щось там тестове", 
    "title": "Тестовий лот", 
    "lotType": "basic", 
    "dateModified": "2018-01-15T15:33:04.952634+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "date": "2018-01-15T15:33:04.952462+02:00", 
    "id": "34b371dc3b8f47a0869a8cac45be1181", 
    "assets": [
      "d7017f6e2c474d4fa8b25f8363b45d70"
    ]
  }
}

