PATCH /api/2.4/lots/fd2bb96b7f2c4ec78a38e556cf80441d?acc_token=b2d586bd4408409d9cdeafdba3289478 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 53
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "description": "Lot description modified"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "composing", 
    "lotID": "UA-LR-DGF-2018-05-25-000002", 
    "assets": [
      "83e2013200da46a99e618a23ee840b93"
    ], 
    "lotType": "loki", 
    "dateModified": "2018-05-25T18:39:52.049683+03:00", 
    "owner": "broker", 
    "auctions": [
      {
        "status": "scheduled", 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "36c04fc7eb994128beaef7a49a02f132"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "d01782a9cc6042cbaa71cebd3cc4bcaa"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "id": "1220de3b020b4a88823ebb87908a0201"
      }
    ], 
    "date": "2018-05-25T18:39:52.049450+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-05-25T18:39:50.545256+03:00", 
        "decisionID": "decisionLotID"
      }
    ], 
    "id": "fd2bb96b7f2c4ec78a38e556cf80441d"
  }
}

