PATCH /api/2.5/lots/9d44d47e1beb4f1d95ea663f9f69274b?acc_token=b802c036c44948f5a1c2bc0df06d1844 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "composing"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "composing", 
    "lotID": "UA-LR-DGF-2018-08-21-000003", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "a117b8aa709e4c1aa6e9e69bb041664b"
      }
    ], 
    "lotType": "loki", 
    "dateModified": "2018-08-21T17:17:27.950335+03:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2018-08-21T17:17:27.874113+03:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2018-08-21T17:17:27.874134+03:00", 
        "id": "dc4eb5d344374a1caddee3a5d9575204"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "id": "fd1b76b890d44b879106f4371bc8fc53", 
        "auctionParameters": {
          "type": "english"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 744.6
        }
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "id": "3a433affcbd342a4b2b0ffb54f0c86a7", 
        "auctionParameters": {
          "type": "english"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 744.6
        }
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "id": "b58423542aa348de95274522f050a314", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 744.6
        }
      }
    ], 
    "date": "2018-08-21T17:17:27.950151+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-08-21T17:17:27.417194+03:00", 
        "decisionID": "initialDecisionID", 
        "id": "45cc20deb9384a8d82c2e30460c17453", 
        "decisionOf": "lot"
      }
    ], 
    "id": "9d44d47e1beb4f1d95ea663f9f69274b"
  }
}

