PATCH /api/2.4/lots/d643a4ad34414779a15fc9c00c229efa?acc_token=e995182bb02246e895b85a7efa0c9e32 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "composing"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "composing", 
    "lotID": "UA-LR-DGF-2018-05-25-000002", 
    "assets": [
      "964e194e98b14d1da03fc48be7865221"
    ], 
    "lotType": "loki", 
    "dateModified": "2018-05-25T17:28:38.807676+03:00", 
    "owner": "broker", 
    "auctions": [
      {
        "status": "scheduled", 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "b6cbe635f04a4be186cf5c23cc4e0c4c"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "5cbe9610176a43afbf624c1d79de0239"
      }, 
      {
        "status": "scheduled", 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "id": "9d847f4e98aa461eab42cfc3d2391f90"
      }
    ], 
    "date": "2018-05-25T17:28:38.807355+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-05-25T17:28:37.300221+03:00", 
        "decisionID": "decisionLotID"
      }
    ], 
    "id": "d643a4ad34414779a15fc9c00c229efa"
  }
}

