PATCH /api/2.5/lots/f2bb47f00ba54ce1beba70d442fa934d/contracts/b5d4265a0dd746bdac85effb9ff4139c HTTP/1.0
Authorization: Basic Y2FyYXZhbjo=
Content-Length: 32
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "complete"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "complete", 
    "type": "yoke", 
    "id": "b5d4265a0dd746bdac85effb9ff4139c"
  }
}

