PATCH /api/2.4/lots/a841c1bfa69d46d6b5c2e640a119f0c9 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Content-Length: 31
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "invalid"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "invalid", 
    "lotID": "UA-LR-DGF-2018-05-25-000003", 
    "assets": [
      "4ea8891f91674800aae50fbd13f49bce"
    ], 
    "lotType": "loki", 
    "dateModified": "2018-05-25T17:29:19.908529+03:00", 
    "owner": "broker", 
    "auctions": [
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2018-05-30T17:28:37.300003+03:00", 
          "endDate": "2018-06-04T17:28:37.300003+03:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.0
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "0cc8bc1a9bf8450a86249ec3db1a5b32", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.0
        }
      }, 
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 350.0
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "a475097a6cc4455e8c315f612058765e", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.0
        }
      }, 
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 350.0
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "bc435fb0614a423480c7d883fcbeb4ff", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.0
        }
      }
    ], 
    "date": "2018-05-25T17:29:19.908330+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-05-25T17:28:37.300221+03:00", 
        "decisionID": "decisionLotID"
      }, 
      {
        "decisionDate": "2018-05-25T17:29:19.766479+03:00", 
        "decisionID": "decisionAssetID"
      }
    ], 
    "id": "a841c1bfa69d46d6b5c2e640a119f0c9"
  }
}

