PATCH /api/2.4/lots/2f01e3ce40454ddabdc521f35a3fcff1?acc_token=ac7314abc1f847dfab998cbb48a76169 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Content-Length: 31
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending", 
    "rectificationPeriod": {
      "startDate": "2018-05-25T18:40:39.423574+03:00", 
      "endDate": "2018-05-27T18:40:39.423574+03:00"
    }, 
    "lotID": "UA-LR-DGF-2018-05-25-000004", 
    "assets": [
      "838bd7a94eae4f4f95b0cbd029c8daa5"
    ], 
    "lotType": "loki", 
    "dateModified": "2018-05-25T18:40:39.432996+03:00", 
    "owner": "broker", 
    "next_check": "2018-05-27T18:40:39.423574+03:00", 
    "auctions": [
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2018-05-30T18:39:50.545034+03:00", 
          "endDate": "2018-06-04T18:39:50.545034+03:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.0
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "283e3f24ea9f4318836ecbf91e1d811a", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.0
        }
      }, 
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 350.0
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "b24fdf3cb6464a449f0623ab0141afd8", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.0
        }
      }, 
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 350.0
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "4737d16e578948f8a80d6e80d7a0de1e", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.0
        }
      }
    ], 
    "date": "2018-05-25T18:40:39.432787+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-05-25T18:39:50.545256+03:00", 
        "decisionID": "decisionLotID"
      }, 
      {
        "decisionDate": "2018-05-25T18:40:39.293849+03:00", 
        "decisionID": "decisionAssetID"
      }
    ], 
    "id": "2f01e3ce40454ddabdc521f35a3fcff1"
  }
}

