PATCH /api/2.4/lots/0d2d80b9cea74839a7861ef787a5090b HTTP/1.0
Authorization: Basic Y29udm95Og==
Content-Length: 36
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "pending.sold"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending.sold", 
    "rectificationPeriod": {
      "startDate": "2018-05-22T17:29:21.986043+03:00", 
      "endDate": "2018-05-23T17:29:21.986043+03:00"
    }, 
    "lotID": "UA-LR-DGF-2018-05-25-000006", 
    "assets": [
      "4ea8891f91674800aae50fbd13f49bce"
    ], 
    "title": "title", 
    "lotType": "loki", 
    "dateModified": "2018-05-25T17:29:22.376408+03:00", 
    "owner": "broker", 
    "next_check": "2018-05-23T17:29:21.986043+03:00", 
    "auctions": [
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2018-05-30T17:28:37.300003+03:00", 
          "endDate": "2018-06-04T17:28:37.300003+03:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.0
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "3f943f2c2cba41d18b1abf7053fe567e", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.0
        }
      }, 
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 350.0
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "cd31715e0de449f7b87127bbf4245c8d", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.0
        }
      }, 
      {
        "status": "scheduled", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 350.0
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "66198c8962ef4a14b56517f45d101570", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.0
        }
      }
    ], 
    "date": "2018-05-25T17:29:22.376205+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-05-25T17:29:21.996744+03:00", 
        "decisionID": "decisionAssetID"
      }, 
      {
        "decisionDate": "2018-05-25T17:29:21.996769+03:00", 
        "decisionID": "decisionAssetID"
      }
    ], 
    "id": "0d2d80b9cea74839a7861ef787a5090b"
  }
}

