PATCH /api/2.5/lots/7004db3cde7b4df3bc0c8166ec55c09b/auctions/ccd4bf0c1a4e4521ab27f447a7168999 HTTP/1.0
Authorization: Basic Y29udm95Og==
Content-Length: 32
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "complete"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "complete", 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 300.87, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "startDate": "2018-08-23T14:56:45.642186+03:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "procurementMethodType": "sellout.english", 
    "value": {
      "currency": "UAH", 
      "amount": 3000.87, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "ccd4bf0c1a4e4521ab27f447a7168999", 
    "auctionParameters": {
      "type": "english"
    }, 
    "tenderAttempts": 1, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 700.87
    }
  }
}

