PATCH /api/2.5/lots/c8d7ed86665548c0a188905954e2aad5 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Content-Length: 31
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "invalid"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "invalid", 
    "lotID": "UA-LR-DGF-2018-08-17-000001", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "7af0e3b9449d44d8b6c9b6d9d6158f1b"
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2018-08-17T14:51:47.375353+03:00", 
        "decisionID": "initialDecisionID", 
        "id": "f066514229bd4a52801ee6f21a6cef72", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "11111111111111111111111111111111", 
        "decisionDate": "2018-08-17T14:51:47.754488+03:00", 
        "decisionID": "decisionAssetID", 
        "id": "dbe561ee483b42c1817574a8c3c3a59d", 
        "decisionOf": "asset"
      }
    ], 
    "lotType": "loki", 
    "dateModified": "2018-08-17T14:51:47.922400+03:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2018-08-17T14:51:47.381277+03:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2018-08-17T14:51:47.381300+03:00", 
        "id": "a4b855c38f5e433e8b188fe3e5a54b12"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2018-08-23T14:56:45.642186+03:00"
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "cb269ff5ef5d4b5fa2d6d124d8f9f449", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 1, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }, 
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.44, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.43, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "e2a37f76feeb46f0b5163251701bb33d", 
        "auctionParameters": {
          "type": "english"
        }, 
        "tenderAttempts": 2, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }, 
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0.0, 
          "valueAddedTaxIncluded": true
        }, 
        "registrationFee": {
          "currency": "UAH", 
          "amount": 700.87
        }, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.43, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "id": "a34c744724eb4d0b9f7c2caddd33e5f5", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "tenderAttempts": 3, 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }
    ], 
    "date": "2018-08-17T14:51:47.922203+03:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "b9e476d51d424312a933b1923c970239", 
        "relatedProcessID": "480632ff537f41b4834875ddcae271f2"
      }
    ], 
    "id": "c8d7ed86665548c0a188905954e2aad5"
  }
}

