PATCH /api/2.5/lots/1970fefc39a3425a9c892a22ce346a8e HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Content-Length: 38
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "status": "active.auction"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "active.auction", 
    "rectificationPeriod": {
      "startDate": "2019-03-16T15:23:09.482898+02:00", 
      "endDate": "2019-03-17T15:23:09.482898+02:00"
    }, 
    "lotID": "UA-LR-DGF-2019-03-19-000003", 
    "description": "Нежитлове приміщення для збереження насіння", 
    "title": "title", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "2371f3d858834f95a5b9b2fb90be0e29"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "loki", 
    "lotHolder": {
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Власник лоту"
    }, 
    "decisions": [
      {
        "decisionDate": "2019-03-19T15:23:09.500637+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "649144da1b6542afa428e94748af612d", 
        "decisionOf": "lot"
      }, 
      {
        "decisionDate": "2019-03-19T15:23:09.500667+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "ba5bad0413dc4d57ada80ea763e7ac14", 
        "decisionOf": "lot"
      }
    ], 
    "dateModified": "2019-03-19T15:23:09.838147+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Сергій", 
        "email": "segiy@mail.com"
      }, 
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Зберігач лоту", 
      "address": {
        "countryName": "Україна"
      }
    }, 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 300.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2019-03-25T15:28:05.257425+02:00"
        }, 
        "tenderAttempts": 1, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "e897b7f2f35846e58887d74373181f4d", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }, 
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 150.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderAttempts": 2, 
        "procurementMethodType": "sellout.english", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "auctionParameters": {
          "type": "english"
        }, 
        "id": "694f7073643247a69b6eea04ba246802", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }, 
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderAttempts": 3, 
        "procurementMethodType": "sellout.insider", 
        "value": {
          "currency": "UAH", 
          "amount": 1500.44, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderingDuration": "P25DT12H", 
        "auctionParameters": {
          "type": "insider", 
          "dutchSteps": 99
        }, 
        "id": "ae20e7f4b061435197a9338fe057202c", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 350.44
        }
      }
    ], 
    "date": "2019-03-19T15:23:09.837931+02:00", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-19T15:23:08.911837+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-19T15:23:08.911857+02:00", 
        "id": "c836938c84224f9e92453837c80d238c"
      }
    ], 
    "relatedProcesses": [
      {
        "identifier": "UA-AR-P-2018-08-17-000002-1", 
        "type": "asset", 
        "id": "9041e14bec364ea0883346927b67cc1f", 
        "relatedProcessID": "a299abda28e64088bd6d37ee5594c213"
      }
    ], 
    "id": "1970fefc39a3425a9c892a22ce346a8e"
  }
}

